// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chsxlkpfjssedmybztar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoc3hsa3BmanNzZWRteWJ6dGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzE1MzEsImV4cCI6MjA4NzM0NzUzMX0.9wEh63QZPXP47__TxECKiU-WG-c_uAEi1spq4Qtvl14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});